### ISSUE TITLE
Theme crashes when used with jekyll-data

### ISSUE THREAD

**Issue by ronaldtse** [ISO-TC211/jekyll-theme-isotc211#7]
Trace:

```
TypeError: no implicit conversion of nil into String
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-data-1.1.0/lib/jekyll-data/reader.rb:11:in `join'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-data-1.1.0/lib/jekyll-data/reader.rb:11:in `initialize'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-data-1.1.0/lib/jekyll-data.rb:50:in `new'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-data-1.1.0/lib/jekyll-data.rb:50:in `block in <top (required)>'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.6/lib/jekyll/hooks.rb:103:in `block in trigger'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.6/lib/jekyll/hooks.rb:102:in `each'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.6/lib/jekyll/hooks.rb:102:in `trigger'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.6/lib/jekyll/site.rb:34:in `initialize'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.6/lib/jekyll/commands/build.rb:30:in `new'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.6/lib/jekyll/commands/build.rb:30:in `process'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.6/lib/jekyll/commands/build.rb:18:in `block (2 levels) in init_with_program'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
  /Users/user/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/jekyll-3.8.6/exe/jekyll:15:in `<top (required)>'
  /Users/user/.rbenv/versions/2.5.1/bin/jekyll:23:in `load'
```

The reason is this line in the `jekyll-data` gem version 1.1:
https://github.com/ashmaroli/jekyll-data/blob/1c0b048f7c1d8146b0808fee5263b7b06b1fa6de/lib/jekyll-data/reader.rb#L10
```ruby
      @theme_data_files = Dir[File.join(site.theme.data_path, "**", "*.{yaml,yml,json,csv,tsv}")]
```

`site.theme.data_path` is empty because our theme gem does not contain the `_data/` folder.

I have done a fix and will push+release it shortly.

**Comment by ronaldtse** [comment]
Fixed in 8c8f2e50cacaf41f2008a4ae89c61df66315b6b7
